name: Lint

on: [push]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Run ESLint
        run: node ./node_modules/eslint/bin/eslint.js -c .eslintrc.js --fix --ext .js,.vue --ignore-path .gitignore .
